import './globals.css';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/Footer';


export const metadata = {
  title: 'Classics',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <div className='overflow-x-hidden w-[100vw]'>
                <Navbar />
        {children}
        <Footer />
        </div>
  
      </body>
    </html>
  )
}
